import os
os.system('pip install --upgrade pip')
os.system('pip install pandagui')
os.system('pip install lxml')
os.system('pip install dtale')
os.system('pip install flask')
os.system('pip install nbopen')
os.system('pip install psycopg2')
os.system('pip install bs4')
os.system('pip install chembl_webresource_client')
os.system('pip install py3Dmol')
os.system('pip install nglview')
os.system('pip install streamlit')
os.system('pip install cirpy')
os.system('pip install xlsxwriter')
os.system('pip install rdkit')
# os.system('pip install XlsxWriter')
# os.system('pip install PubChemPy')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
# os.system('pip install lxml')
